# Generated by Django 5.0 on 2024-01-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_category_status_remove_category_trending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='trending',
            field=models.BooleanField(default=False, help_text='0=default, 1=Trending'),
        ),
    ]
